config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get '/contacts', :to => 'contacts#index'
    get '/contacts/:key', :to => 'contacts#show', :as => :contact
  end

  root :to => 'site#home'
  get '/prices' => 'site#prices'
  get '/aboutus' => 'site#aboutus'
  get '/contact' => 'site#contact'
  
  namespace :api do
    get '/contacts'                     => 'contacts#index'
    get '/contacts/key/:key'            => 'contacts#showbykey'
    get '/contacts/:id'                 => 'contacts#show', :as => :contact
    put '/contacts/key/:key'            => 'contacts#update'
    post '/contacts/key/:key/addvisit'  => 'contacts#addvisit'
    post '/contacts'                    => 'contacts#create'
  end
end

app/models/api/contact.rb
class Api::Contact < ActiveRecord::Base
  has_many :visits, dependent: :destroy
  validates_presence_of :key
  validates_uniqueness_of :key
end

app/models/api/visit.rb
class Api::Visit < ActiveRecord::Base
  belongs_to :contact
  before_save :set_when
  validates_presence_of :page, :contact

  def set_when
    self.when = Time.new
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :visits, dependent: :destroy
  validates_presence_of :key
  validates_uniqueness_of :key
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :contact
  before_save :set_when
  validates_presence_of :page, :contact

  def set_when
    self.when = Time.new
  end
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  def index
    @contacts = Api::Contact.all
  end

  def show
    @contact = Api::Contact.find_by_key params[:key]
  end
end

app/controllers/api/contacts_controller.rb
module Api
  class ContactsController < ApplicationController
    before_action :set_contact_by_key, only: [:showbykey, :update, :addvisit]

    def index
      @contacts = Contact.all
    end

    def showbykey
      if !@contact
        render json: { message: 'Not found.' }, status: :not_found
      end
    end

    def show
      @contact = Contact.find params[:id]
    end

    def create
      @contact = Contact.new contact_params
      respond_to do |format|
        if @contact.save
          format.json { render :show, status: :created, location: @contact }
        else
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @contact.update contact_params
          format.json { render :show, status: :ok, location: @contact }
        else
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end

    def addvisit
      @visit = Visit.new visit_params
      @visit.contact = @contact
      respond_to do |format|
        if (@visit.save) 
          format.json { render :showvisit, status: :created }
        else
          format.json { render json: @visit.errors, status: :unprocessable_entity }
        end
      end
    end

    private
      def set_contact_by_key
        @contact = Contact.find_by_key params[:key]
      end

      def contact_params
        params.permit :key, :name, :email, :message
      end

      def visit_params
        params.permit :page
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact_by_key, only: [:showbykey, :update, :addvisit]

  def index
    @contacts = Contact.all
  end

  def showbykey
  end

  def show
    @contact = Contact.find params[:id]
  end

  def create
    @contact = Contact.new contact_params
    respond_to do |format|
      if @contact.save
        format.json { render :show, status: :created, location: @contact }
      else
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @contact.update contact_params
        format.json { render :show, status: :ok, location: @contact }
      else
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def addvisit
    @visit = Visit.new visit_params
    @visit.contact = @contact
    respond_to do |format|
      if (@visit.save) 
        format.json { render :showvisit, status: :created }
      else
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_contact_by_key
      @contact = Contact.find_by_key params[:key]
    end

    def contact_params
      params.permit :key, :name, :email, :message
    end

    def visit_params
      params.permit :page
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end

  def prices
  end

  def aboutus
  end

  def contact
  end
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/api/contacts_helper.rb
module Api::ContactsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admin/contacts/index.html.erb
<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.sort {|a,b| b.created_at <=> a.created_at}.each do |contact| %>
      <tr>
        <td><%= contact.key %></td>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', admin_contact_path(contact.key) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/contacts/show.html.erb
<h1>Info about <%= @contact.name %></h1>

<p>
  <strong>Key:</strong>
  <%= @contact.key %>
</p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<h2>Visits</h2>

<table>
  <thead>
    <tr>
      <th>Page</th>
      <th>When?</th>
    </tr>
  </thead>
  <tbody>
    <% @contact.visits.sort {|a,b| b.when <=> a.when}.each do |visit| %>
      <tr>
        <td><%= visit.page %></td>
        <td><%= visit.when.strftime('%d-%m-%Y %H:%M') %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserTrackerRd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <ul>
    <li><%= link_to 'Home', root_path, :id => 'home', :onclick => 'pageVisited(this.id)' %> | </li>
    <li><%= link_to 'Prices', prices_path, :id => 'prices', :onclick => 'pageVisited(this.id)' %> | </li>
    <li><%= link_to 'About us', aboutus_path, :id => 'aboutus', :onclick => 'pageVisited(this.id)' %> | </li>
    <li><%= link_to 'Contact', contact_path, :id => 'contact', :onclick => 'pageVisited(this.id)' %> | </li>
    <!-- TODO (URGENT) This link should be hidden for default users -->
    <li><%= link_to 'List contacts', admin_contacts_path %></li>
  </ul>

  <%= yield %>

</body>
</html>

app/views/site/aboutus.html.erb
<h1>About us</h1>

<p>We are awesome!</p>

app/views/site/contact.html.erb
<h1>Contact</h1>
<form action="#" onsubmit="submitForm(event, this)">
  <label for="name">Name</label><br>
  <input type="text" id="name" name="name" placeholder="Name"><br>
  <label for="email">Email</label><br>
  <input type="email" id="email" name="email" placeholder="Email"><br>
  <label for="message">Message</label><br>
  <textarea id="message" name="message" placeholder="Message" cols="30" rows="5"></textarea><br>
  <button type="submit">Send</button>
</form>

app/views/site/home.html.erb
<h1>Home</h1>

<p>Hey, this is the home page, dude!</p>

app/views/site/prices.html.erb
<h1>Prices</h1>

<ol>
  <li>Cupcake: US$ 2,00</li>
  <li>Marshmallows: US$ 3,00</li>
  <li>Medkit: US$ 10,00</li>
</ol>